version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - '3000:80'
    depends_on:
      - php
      - mysql
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - mysql:db
  php:
    image: php:7-fpm
    volumes:
      - ./code:/code
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.5.3.1-1
    ports:
      - '8080:8080'
    #depends_on:
    #  - mysql
    links:
      - mysql:db
    volumes:
      - './phpmyadmin/sessions:/sessions'
