version: '3'

services:
  web:
    hostname: sample-app
    container_name: sample-app
    build: ./nginx
    ports:
      - '3000:80'
    depends_on:
      - php
      - mysql
    links:
      - php
      - mysql
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    hostname: sample-php
    container_name: sample-php
    build: ./php
    volumes:
      - ./code:/code

  mysql:
    hostname: sample-db
    container_name: sample-db
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker

  phpmyadmin:
    hostname: sample-pma
    container_name: sample-pma
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - '8080:80'
    volumes:
      - /sessions
