version: '3'

services:
  web:
    image: nginx:latest
    hostname: app
    container_name: app
    ports:
      - '3000:80'
    depends_on:
      - php
      - mysql
    links:
      - php
      - mysql
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7-fpm
    volumes:
      - ./code:/code

  mysql:
    hostname: db
    container_name: db
    build: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: docker

  phpmyadmin:
    hostname: pma
    container_name: pma
    build: ./phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - '8080:80'
    volumes:
      - /sessions
